__include__: [
  '../configs/rtdetrv2/rtdetrv2_r50vd_6x_coco.yml',
]

num_classes: 3

print_freq: 10
checkpoint_freq: 10
save_optimizer: false
save_ema: true
output_dir: output/normal

remap_mscoco_category: True
RTDETRPostProcessor:
  num_top_queries: 300

use_amp: True
use_ema: True 
ema:
  type: ModelEMA
  decay: 0.999
  warmups: 500

epoches: 200
clip_max_norm: 5.0

lr_scheduler:
  type: MultiStepLR  # CosineAnnealingLR | OneCycleLR
  milestones: [180]  # epochs
  gamma: 0.1

lr_warmup_scheduler:
  type: LinearWarmup
  warmup_duration: 500  # steps

train_dataloader:
  dataset:
    type: SSLDataset
    img_folder: data/insulator-defect-detection/sly_project/train/img
    ann_file: data/insulator-defect-detection/coco_ann/train/annotations/coco_instances.json
    # unlabeled_img_folder: data/insulator-defect-detection/sly_project/train/img
    sample_mode: True
    labeled_sample_size: 125
    unlabeled_sample_size: 0
    transforms:
      policy:
        name: stop_epoch
        epoch: 150 # epoch in [150, ~) stop `ops`
        ops: ['RandomPhotometricDistort', 'RandomZoomOut', 'RandomIoUCrop']
  total_batch_size: 8
  num_workers: 8
  collate_fn:
    type: SSLBatchImageCollateFunction
    stop_epoch: 150

val_dataloader:
  dataset:
    img_folder: data/insulator-defect-detection/sly_project/val/img
    ann_file: data/insulator-defect-detection/coco_ann/val/annotations/coco_instances.json
  total_batch_size: 8
  num_workers: 8